### ISSUE TITLE
Taking pictures does not work

### ISSUE THREAD

**Issue by tommytomtom666** [RichardCardoso/WQC_Server-Side#10]
[LOG_Logging_2020-03-18.txt](https://github.com/RichardCardoso/WQC_Server-Side/files/4348935/LOG_Logging_2020-03-18.txt)
[SEVERE_Logging_2020-03-18.txt](https://github.com/RichardCardoso/WQC_Server-Side/files/4348937/SEVERE_Logging_2020-03-18.txt)
[WARNING_Logging_2020-03-18.txt](https://github.com/RichardCardoso/WQC_Server-Side/files/4348938/WARNING_Logging_2020-03-18.txt)

For the QC department we switched to a lenovo tab M8 with android 9.
But when starting the function "taking general pictures" the app closes. Also on my phone it seems not to work propaply. 
Could you please check the log files?

**Comment by tommytomtom666** [comment]
![20200415_113817](https://user-images.githubusercontent.com/35429629/79323474-8a9c7300-7f0e-11ea-9ca1-0ed836d3889b.jpg)
![20200415_113823](https://user-images.githubusercontent.com/35429629/79323485-8c663680-7f0e-11ea-884c-6ae5f0b94bb0.jpg)

### Taking general pictures:

1. Starting function: ok
2. Screen for taking pictures: ok
3. Taking first picture: ok -->number on the top shows up but screen frezzes (see picture attached) 
4. !Hitting the camera button again causes a crash in the app.
5. Starting from point 3 (see above): hitting the return button
6. Preview for uploading picture shows up. Taking one picture again is now possible
7. Upload works.

Comments:
A) It should be possible after taking one picute to take another or
B) Going directly to the upload screen

**Comment by RichardCardoso** [comment]
Solved with update 2.7.1.9
