### ISSUE TITLE
Jumping on top

### ISSUE THREAD

**Issue by tommytomtom666** [RichardCardoso/WQC_Server-Side#11]
![Screenshot_2020-03-18-13-10-35-138](https://user-images.githubusercontent.com/35429629/76961325-79ffd980-691d-11ea-972b-387f4d1e38f6.jpeg)

When the user fills out the sheet the app jumps always back on the top. Which is not so user friendly becuase the list is quite long.

**Comment by RichardCardoso** [comment]
Solved with update 2.7.1.10
